CREATE TABLE IF NOT EXISTS municipality (
    id         BIGSERIAL   PRIMARY KEY,
    slug       VARCHAR(63) NOT NULL UNIQUE,
    active     BOOLEAN     NOT NULL DEFAULT true,
    created_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);
